---
- name: ansible restart runit
  community.general.runit:
    name: flask
    state: restarted
    service_dir: /etc/service
  when: not flask_symlink.failed or flask_runit_template.changed

- name: ansible restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted