---
- name: ansible set timezone to UTC
  community.general.timezone:
    hwclock: UTC

- name: ansible create devops user
  ansible.builtin.user:
    name: "{{ devops_la_challenges_flask_user }}"
    comment: unprivileged user to run flask apps

- name: ansible create dependency directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
  - {
      path: "{{ devops_la_challenges_flask_dir }}",
      owner: "{{ devops_la_challenges_flask_user }}",
      group: "{{ devops_la_challenges_flask_user }}",
      mode: "0755"
    }
  - {
      path: "{{ devops_la_challenges_flask_log_dir }}",
      owner: "{{ devops_la_challenges_flask_user }}",
      group: "{{ devops_la_challenges_flask_user }}",
      mode: "0755"
    }
  - {
      path: "{{ devops_la_challenges_flask_runit_stage_dir }}/flask/log",
      owner: "root",
      group: "root",
      mode: "0755"
    }

- name: ansible render runit template
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}/run"
    owner: root
    group: root
    mode: "0755"
  register: flask_runit_template
  loop:
  - { src: "run.j2", dest: "{{ devops_la_challenges_flask_runit_stage_dir }}/flask" }
  - { src: "log_run.j2", dest: "{{ devops_la_challenges_flask_runit_stage_dir }}/flask/log" }

- name: ansible set ufw
  ansible.builtin.include: ufw-configuration.yml
  loop: "{{ devops_la_challenges_flask_ufw_rules }}"
  loop_control:
    loop_var: ufw_rules
