---
- include_tasks: prepare-dependencies.yml
- include_tasks: general-configuration.yml

- name: ansible clone flask apps repository
  ansible.builtin.git:
    repo: "{{ devops_la_challenges_flask_repository }}"
    dest: "{{ devops_la_challenges_flask_dir }}"
    force: yes
    clone: yes
  become: yes
  become_user: "{{ devops_la_challenges_flask_user|default(omit) }}"

- name: ansible set requirements.txt with version constraints
  ansible.builtin.lineinfile:
    path: "{{ devops_la_challenges_flask_dir }}/requirements.txt"
    regexp: '^Werkzeug'
    line: Werkzeug==0.16.0
  become: yes
  become_user: "{{ devops_la_challenges_flask_user|default(omit) }}"
  notify: ansible install specified python requirements

- name: ansible flush handlers
  meta: flush_handlers