---
# Setup/install dependencies
- include_tasks: prepare-dependencies.yml

# Setup/prepare host machine
- include_tasks: general-configuration.yml

# Setup/configure flask apps
- include_tasks: flask-configuration.yml

