---
- name: ansible install dependency packages
  ansible.builtin.apt:
    update_cache: yes
    name: "{{ devops_la_challenges_flask_dependencies }}"
    state: present

- name: ansible install gunicorn
  ansible.builtin.pip:
    name: "gunicorn=={{ devops_la_challenges_flask_gunicorn_version|default('19.10.0', true) }}"